name: BetterClear
version: '${version}'
main: gg.fullwin.betterclear.BetterClear
api-version: 1.18
authors: [ brawn ]
description: essentials sucks
website: fullwin.gg
commands:
  clear:
    permission: "fullwin.clear"
  speed:
    permission: "fullwin.speed"
  strength:
    permission: "fullwin.strength"
  stats:
    description: "YOUR MUM"
  tpkits:
    description: "YOUR NAN"
  kit delete:
    permission: "fullwin.kit.delete"
    description: "DELETE KIT!"
  kit create:
    permission: "fullwin.kit.create"
    description: "CREATE KIT!"
  kit setinv:
    permission: "fullwin.kit.setinv"
    description: "SET INV KIT!"
  kit getinv:
    permission: "fullwin.kit.getinv"
    description: "GET INV KIT!"
  kit:
    description: "VIEW KIT!"
  build:
    permission: "fullwin.build"
    description: "builder mode"